In [1]:
import os
import numpy as np
import pandas as pd
from typing import Tuple

# Chemical reading files
cassava_chemical_readings = '../spectral_data/cassava-scores and rt-pcr.xlsx' 
maize_chemical_readings = '../spectral_data/Maize Scores and rtpcr.xlsx' 
general_expert_scores = '../spectral_data/ICAIN Disease data.xlsx' 
beans_expert_readings= '../spectral_data/ICAIN Disease data-Beans.xlsx'



# Reading files
cmd_df = pd.read_excel(cassava_chemical_readings, sheet_name='CMD')
cbb_df = pd.read_excel(cassava_chemical_readings, sheet_name= 'CBB')

# attaching remaining chemical readings
os.listdir('../spectral_data')

['spectral_data_week3',
 'spectral_data_week10',
 '.~cassava-scores and rt-pcr.xlsx',
 'Maize Scores and rtpcr.xlsx',
 'spectral_data_week11',
 'cassava-scores and rt-pcr.xlsx',
 'spectral_data_week1',
 'spectral_data_week0',
 'ICAIN Disease data.xlsx',
 'spectral_data_week7',
 'spectral_data_week8',
 'spectral_data_week5',
 'spectral_data_week4',
 'spectral_data_week6',
 'ICAIN Disease data-Beans.xlsx',
 'spectral_data_week2',
 'spectral_data_week9']

In [53]:
week_col = 'CBSD'
week_rows = cmd_df.astype(str).apply(
    lambda row: row.str.contains(r'WEEK\s*\d+', case=False, na=False).any(),
    axis=1
)

cmd_df['week'] = (
    cmd_df[week_col]
    .astype(str)
    .str.extract(r'WEEK\s*(\d+)', expand=False)
)
# apply a forward fill to the vales
cmd_df['week'] = cmd_df['week'].ffill()

# remove rows that contain WEEK labels
cmd_df = cmd_df[
    ~cmd_df[week_col]
    .astype(str)
    .str.contains(r'WEEK', case=False, na=False)
]

# reset index
cmd_df = cmd_df.reset_index(drop=True)

# format the columns correctly
new_col_names = ['plant_number', 'score', 'titer_1', 'l_1' ,'titer_2','l_2', 'titer_3', 'l3', 'week']
col_names = list(cmd_df.columns)
rename_dict = {old_col:new_col for old_col, new_col in zip(col_names, new_col_names)}
cmd_df = cmd_df.rename(columns=rename_dict)

# extracting plant number only
cmd_df['plant_number'] = (
    cmd_df['plant_number']
    .astype(str)
    .str.extract(r'(\d+)')[0]
    .astype(int)
)

# Replacing week with NaN with 1 to not week before innoculation
cmd_df['week'] = cmd_df['week'].fillna(1)
cmd_df['disease_class'] = 'CMD'
cmd_df

,plant_number,score,titer_1,l_1,titer_2,l_2,titer_3,l3,week,disease_class
0,1,1,undetected,N,Undetected,N,Undetected,N,1,CMD
1,2,1,undetected,N,Undetected,N,Undetected,N,1,CMD
2,3,1,36.224435,T,Undetected,N,Undetected,N,1,CMD
3,4,1,undetected,N,Undetected,N,Undetected,N,1,CMD
4,5,1,undetected,N,Undetected,N,Undetected,N,1,CMD
5,1,1,35.290593,WP,Undetected,N,36.401321,P,2,CMD
6,2,1,undetected,N,Undetected,N,36.701332,P,2,CMD
7,3,2,32.411178,P,Undetected,N,36.701332,N,2,CMD
8,4,1,34.812006,P,35.474634,P,37.301354,P,2,CMD
9,5,1,33.611592,P,35.889542,P,37.301354,N,2,CMD
10,1,1,29.763023,P,30.452288,P,34.691468,P,3,CMD
11,2,2,30.266206,P,33.749364,P,34.999381,P,3,CMD
12,3,2,27.558355,SP,29.450568,P,33.254544,P,3,CMD
13,4,2,30.163872,P,29.751084,P,32.433444,P,3,CMD
14,5,1,22.961326,P,32.949708,P,33.459818,P,3,CMD
15,1,2,25.30923,SP,24.467666,P,28.41072,SP,4,CMD
16,2,2,32.810142,SP,31.272658,P,29.211022,SP,4,CMD
17,3,3,28.60861,SP,28.868775,P,27.410343,SP,4,CMD
18,4,2,26.409632,SP,25.871548,P,27.610418,SP,4,CMD
19,5,2,28.909084,SP,29.969052,P,29.710456,SP,4,CMD
20,1,3,22.108063,VSP,20.95796,VSP,20.4077,VSP,5,CMD
21,2,3,29.308865,VSP,29.467666,VSP,29.209135,VSP,5,CMD
22,3,3,26.507479,VSP,27.462119,VSP,27.608531,VSP,5,CMD
23,4,3,25.008391,VSP,25.866002,VSP,23.608908,VSP,5,CMD
24,5,2,28.807953,VSP,28.966279,VSP,28.708946,VSP,5,CMD
25,1,3,19.407078,VSP,19.4538,VSP,20.4077,VSP,6,CMD
26,2,3,28.707917,VSP,28.451027,VSP,28.607776,VSP,6,CMD
27,3,3,24.806494,VSP,24.952413,VSP,24.008304,VSP,6,CMD
28,4,3,20.20737,VSP,18.451027,VSP,21.408078,VSP,6,CMD
29,5,3,25.906895,VSP,25.456573,VSP,25.4077,VSP,6,CMD
30,1,3,17.506385,VSP,18.451027,VSP,18.306908,VSP,7,CMD
31,2,3,27.807224,VSP,27.84659,VSP,27.806719,VSP,7,CMD
32,3,4,21.605691,VSP,21.946867,VSP,21.406945,VSP,7,CMD
33,4,3,21.306676,VSP,21.247699,VSP,21.406568,VSP,7,CMD
34,5,4,24.906166,VSP,24.648808,VSP,23.906757,VSP,7,CMD
35,1,4,15.205545,VSP,15.34243,VSP,15.906002,VSP,8,CMD
36,2,4,25.405618,VSP,25.442707,VSP,25.605889,VSP,8,CMD
37,3,4,19.905436,VSP,19.941321,VSP,19.405813,VSP,8,CMD
38,4,4,17.905801,VSP,19.244926,VSP,19.00604,VSP,8,CMD
39,5,4,2.005837,VSP,21.44548,VSP,21.906002,VSP,8,CMD

In [54]:
cbb_df

# checking weeks with week anotations
week_col = 'Cassava bacterial blight'
week_mask = cbb_df.iloc[:, 0].astype(str).str.match(r'^\s*week\s*\d+', case=False, na=False)
cbb_df['week'] = cbb_df.iloc[:, 0].where(week_mask).str.extract(r'(\d+)', expand=False)
cbb_df['week'] = cbb_df['week'].ffill()
cbb_df = cbb_df[~week_mask].copy()
cbb_df = cbb_df.drop(0).reset_index(drop=True)

# format column names
new_col_names = ['plant_number', 'description', 'score' ,'titer_1', 'l_1' ,'titer_2','l_2', 'titer_3', 'l2', 'week']
col_names = list(cbb_df.columns)
rename_dict = {old_col:new_col for old_col, new_col in zip(col_names, new_col_names)}
cbb_df = cbb_df.rename(columns=rename_dict)

# extracting plant number only
cbb_df['plant_number'] = (
    cbb_df['plant_number']
    .astype(str)
    .str.extract(r'(\d+)')[0]
    .astype(int)
)
cbb_df['disease_class'] = 'CBB'
cbb_df = cbb_df.drop(columns= ['description'])

cbb_df.head(50)

,plant_number,score,titer_1,l_1,titer_2,l_2,titer_3,l2,week,disease_class
0,1,1,38.260261,0,38.65777,0,38.65777,NaN,1,CBB
1,2,1,39.75092,0,39.75092,0,39.75092,NaN,1,CBB
2,3,1,38.757147,0,39.75092,0,39.75092,NaN,1,CBB
3,4,1,39.75092,0,39.75092,0,39.75092,NaN,1,CBB
4,5,1,39.75092,0,39.75092,0,39.75092,NaN,1,CBB
5,1,1,38.03436,NaN,37.874078,NaN,38.60225,NaN,2,CBB
6,2,1,39.2418,NaN,39.284283,NaN,39.702509,NaN,2,CBB
7,3,1,37.7325,NaN,39.787927,NaN,38.502433,NaN,2,CBB
8,4,1,39.7449,NaN,39.284283,NaN,38.60244,NaN,2,CBB
9,5,1,40.248,NaN,39.284283,NaN,38.702446,NaN,2,CBB
10,1,1,36.6891,NaN,37.84492,NaN,37.402111,NaN,3,CBB
11,2,2,31.1922,NaN,28.707745,NaN,32.802073,NaN,3,CBB
12,3,1,33.2046,NaN,35.053668,NaN,36.802326,NaN,3,CBB
13,4,2,38.2356,NaN,37.67262,NaN,38.402427,NaN,3,CBB
14,5,2,39.2418,NaN,38.377722,NaN,38.60244,NaN,3,CBB
15,1,2,33.1736,NaN,34.513576,NaN,33.202098,NaN,4,CBB
16,2,2,27.1674,NaN,28.909203,NaN,32.402048,NaN,4,CBB
17,3,2,35.1736,NaN,30.722324,NaN,34.202414,NaN,4,CBB
18,4,2,36.1984,NaN,37.923782,NaN,35.402111,NaN,4,CBB
19,5,1,38.2356,NaN,37.471162,NaN,38.502433,NaN,4,CBB
20,1,2,30.6271,NaN,31.958907,NaN,27.301725,NaN,5,CBB
21,2,2,26.6147,NaN,27.066925,NaN,29.901574,NaN,5,CBB
22,3,2,32.1674,NaN,28.607016,NaN,29.501864,NaN,5,CBB
23,4,2,31.1922,NaN,34.147107,NaN,34.802199,NaN,5,CBB
24,5,2,35.217,NaN,35.456583,NaN,35.202225,NaN,5,CBB
25,1,2,27.6085,NaN,29.541412,NaN,28.401795,NaN,6,CBB
26,2,3,25.79734,NaN,28.951617,NaN,28.301789,NaN,6,CBB
27,3,3,30.1488,NaN,27.599727,NaN,29.401858,NaN,6,CBB
28,4,2,29.1798,NaN,32.700456,NaN,29.301852,NaN,6,CBB
29,5,2,33.2046,NaN,31.628884,NaN,30.101902,NaN,6,CBB
30,1,3,25.6147,NaN,26.583426,NaN,24.201529,NaN,7,CBB
31,2,3,26.1116,NaN,27.944328,NaN,24.301536,NaN,7,CBB
32,3,3,22.1364,NaN,26.693166,NaN,24.801567,NaN,7,CBB
33,4,3,30.1612,NaN,30.801185,NaN,30.801757,NaN,7,CBB
34,5,2,30.186,NaN,29.715034,NaN,30.801947,NaN,7,CBB
35,1,3,25.69672,NaN,25.555991,NaN,24.001264,NaN,8,CBB
36,2,3,26.1178,NaN,24.47713,NaN,24.401352,NaN,8,CBB
37,3,3,20.22462,NaN,23.599727,NaN,24.401542,NaN,8,CBB
38,4,3,29.95376,NaN,28.607016,NaN,29.401858,NaN,8,CBB
39,5,2,29.58228,NaN,31.02451,NaN,29.801883,NaN,8,CBB
40,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,CBB
41,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,CBB
42,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,CBB
43,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,CBB
44,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,CBB
45,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,CBB
46,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,CBB
47,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,CBB
48,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,CBB
49,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,CBB

In [55]:
## cleaning the maize expert file
maize_df = pd.read_excel(maize_chemical_readings)
week_mask = maize_df.iloc[:, 0].astype(str).str.match(
    r'^\s*week\s+\d+\s*$',
    case=False,
    na=False
)
maize_df['week'] = maize_df.iloc[:, 0].where(week_mask).str.extract(r'(\d+)', expand=False)
maize_df['week'] = maize_df['week'].ffill()
maize_df['week'] = maize_df['week'].fillna(1)

maize_df = maize_df.drop(columns={'week 1', 'Disease description'})

# format column names
def rename_df(df: pd.DataFrame):
    new_col_names= ['plant_number', 'score', 'titer_1', 'l_1', 'titer_2', 'l_2', 'titer_3', 'l3', \
                     'week', 'disease_class']
    col_names = list(df.columns)
    rename_dict = {old_col: new_col for old_col, new_col in zip(col_names, new_col_names)}
    return df.rename(columns= rename_dict)


# splitting the dataframe
split_idx = maize_df.columns.get_loc('Symptom description.1')

# creating and populating the mln meta data
mln_df = maize_df.iloc[:, :split_idx + 1]
mln_df['week'] = maize_df['week']
mln_df['disease_class'] = 'MLN'


#  creating and population the msv meta data
msv_df = maize_df.iloc[:, split_idx + 1:]
msv_df['DAY'] = maize_df['DAY']
msv_df['score'] = maize_df['score']
msv_df['disease_class'] = 'MSV'

# rearrange the positions for msv_df and perform renaming 
msv_df = msv_df[['DAY', 'score', 'MSV1', 'Symptom description (A= asymptomatic, S=Symptom)', 'MLN2',
       'Unnamed: 13', 'MLN3.1', 'Unnamed: 15', 'week','disease_class']]

mln_df = rename_df(mln_df)
msv_df = rename_df(msv_df)

# mln_df
msv_df

,plant_number,score,titer_1,l_1,titer_2,l_2,titer_3,l3,week,disease_class
0,1,1,38.114760,A,39.737000,A,38.07600,A,1,MSV
1,2,1,39.318384,A,38.630400,A,39.27840,A,1,MSV
2,3,1,38.415666,A,39.535800,A,38.37660,A,1,MSV
3,4,1,39.518988,A,39.938200,A,39.47880,A,1,MSV
4,5,1,39.719592,A,39.535800,A,39.67920,A,1,MSV
5,1,1,38.515968,A,39.636400,A,38.47680,A,2,MSV
6,2,1,39.518988,A,37.926200,A,39.47880,A,2,MSV
7,3,1,38.315364,A,38.026800,A,38.27640,A,2,MSV
8,4,1,38.515968,A,38.529800,A,38.47680,A,2,MSV
9,5,1,38.515968,A,38.630400,A,38.47680,A,2,MSV
10,1,1,37.512948,A,38.026800,A,37.47480,A,3,MSV
11,2,1,38.515968,A,37.121400,A,38.47680,A,3,MSV
12,3,1,38.415666,A,36.920200,A,38.37660,A,3,MSV
13,4,1,37.412646,A,37.423200,A,37.37460,A,3,MSV
14,5,1,37.512948,A,37.926200,A,37.47480,A,3,MSV
15,1,2,36.309324,A,37.725000,A,36.27240,A,4,MSV
16,2,2,36.911136,A,36.719000,A,36.87360,A,4,MSV
17,3,2,37.512948,A,36.719000,A,37.47480,A,4,MSV
18,4,2,37.512948,A,35.914200,A,37.47480,A,4,MSV
19,5,2,37.914156,A,36.115400,A,37.87560,A,4,MSV
20,1,2,35.520474,A,36.517800,A,35.87160,A,5,MSV
21,2,2,35.917350,A,35.511800,A,36.35204,A,5,MSV
22,3,2,36.909542,A,35.109400,A,37.35624,A,5,MSV
23,4,2,37.901734,A,35.210000,A,38.36044,A,5,MSV
24,5,2,38.100173,A,35.109400,A,38.56128,A,5,MSV
25,1,3,34.627501,A,35.511800,A,35.04658,A,6,MSV
26,2,3,35.520474,A,36.527860,A,35.95036,A,6,MSV
27,3,3,35.917350,A,33.801600,A,36.35204,A,6,MSV
28,4,3,35.520474,A,33.902200,A,35.95036,A,6,MSV
29,5,3,35.619693,A,36.749180,A,36.05078,A,6,MSV
30,1,3,33.932966,A,32.292600,A,34.34364,A,7,MSV
31,2,3,34.032186,A,32.795600,A,34.44406,A,7,MSV
32,3,3,34.528282,A,35.427084,A,34.94616,A,7,MSV
33,4,3,34.627501,A,32.106420,A,35.04658,A,7,MSV
34,5,3,34.032186,A,31.206240,A,34.44406,A,7,MSV
35,1,3,33.139213,MS,31.006200,MS,33.54028,MS,8,MSV
36,2,3,32.940774,MS,31.506300,MS,33.33944,MS,8,MSV
37,3,3,33.436870,Ms,33.516702,Ms,33.84154,Ms,8,MSV
38,4,3,33.932966,MS,31.806360,MS,34.34364,MS,8,MSV
39,5,3,33.734528,MS,30.806160,MS,34.14280,MS,8,MSV
40,1,3,32.742336,Ms,30.806160,Ms,33.13860,Ms,9,MSV
41,2,3,32.742336,MS,30.416082,MS,33.13860,MS,9,MSV
42,3,3,31.948582,MS,30.206040,MS,32.33524,MS,9,MSV
43,4,3,32.147021,Ms,30.606120,Ms,32.53608,Ms,9,MSV
44,5,3,32.543898,MS,29.605920,MS,32.93776,MS,9,MSV
45,1,3,31.551706,MS,31.656330,MS,31.93356,MS,10,MSV
46,2,3,31.154829,Ms,29.305860,Ms,31.53188,Ms,10,MSV
47,3,3,31.254048,MS,29.205840,MS,31.63230,MS,10,MSV
48,4,3,31.154829,MS,29.605920,MS,31.53188,MS,10,MSV
49,5,3,31.551706,Ms,32.326464,Ms,31.93356,Ms,10,MSV

In [2]:
# reading beans dataset
beans_df = pd.read_excel(beans_expert_readings)
original_df= beans_df

first_col = beans_df.columns[0]
beans_df[first_col]

# remove emty rows
beans_df = beans_df.dropna(how='all').reset_index(drop=True)

# detect rows containing dates
date_mask = beans_df[first_col].astype(str).str.match(
    r'^\s*\d{1,2}(st|nd|rd|th)?\s+[A-Za-z]+\s*$',
    case= False,
    na= False
)

# create week numbers from detected datas
beans_df.loc[date_mask, 'week'] = range(1, date_mask.sum() + 1)


# forward_fill values downwards
beans_df['week'] = beans_df['week'].ffill()

# fill mising weeks with 0
beans_df['week'] = beans_df['week'].fillna(0)

# remove date rows 
beans_df = beans_df[~date_mask].reset_index(drop=True)

# increment the weeks to match the data
beans_df['week'] = beans_df['week'] + 1

beans_df

plant_col ='Plant No'
last_Value= None
for idx in beans_df.index:
    current = beans_df.loc[idx, plant_col]
    # if current value exits, updated tracker
    if pd.notna(current):
        last_value = int(current)
    # if Nan, continue sequence
    else:
        if last_value is None:
            last_value = 1
        else:
            last_value = (last_value % 5) + 1
        beans_df.loc[idx, plant_col] = last_value
beans_df

# drop fully empty column
beans_df = beans_df.dropna(axis=1, how='all')

beans_df.columns=[
    'plant_number',
    'disease_description',
    'plant_1',
    'plant_2',
    'plant_3',
    'elisa_score_1',
    'elisa_score_2',
    'elisa_score_3',
    'week'
]
beans_df = beans_df.drop(columns=['disease_description'])

beans_df['score'] = beans_df[
    ['plant_1', 'plant_2', 'plant_3']
].mean(axis=1).astype(int)

beans_df = beans_df.drop(columns=['plant_1', 'plant_2', 'plant_3'])

beans_df['l_1'] = np.nan
beans_df['l_2'] = np.nan
beans_df['l_3'] = np.nan
beans_df['disease_class'] = np.nan


# renaming
rename_keys= {f'elisa_score_{i+1}': f'titer_{i+1}' for i in range(3)}
beans_df = beans_df.rename(columns=rename_keys)
#  reordering the columns for consistent merger
beans_df = beans_df[['plant_number', 'score', 'titer_1', 'l_1', 'titer_2', 'l_2', 'titer_3',\
                     'l_3', 'week', 'disease_class']]


beans_df

,plant_number,score,titer_1,l_1,titer_2,l_2,titer_3,l_3,week,disease_class
0,1,1,0.32,NaN,0.34,NaN,0.33,NaN,1.0,NaN
1,2,1,0.35,NaN,0.33,NaN,0.33,NaN,1.0,NaN
2,3,1,0.33,NaN,0.32,NaN,0.33,NaN,1.0,NaN
3,4,1,0.34,NaN,0.31,NaN,0.33,NaN,1.0,NaN
4,5,1,0.34,NaN,0.34,NaN,0.35,NaN,1.0,NaN
5,1,1,0.42,NaN,0.85,NaN,0.44,NaN,2.0,NaN
6,2,1,0.45,NaN,0.55,NaN,0.48,NaN,2.0,NaN
7,3,1,0.52,NaN,0.52,NaN,0.43,NaN,2.0,NaN
8,4,1,0.39,NaN,0.54,NaN,0.45,NaN,2.0,NaN
9,5,1,0.39,NaN,0.45,NaN,0.43,NaN,2.0,NaN
10,1,2,0.77,NaN,0.87,NaN,0.79,NaN,3.0,NaN
11,2,2,0.74,NaN,0.73,NaN,0.74,NaN,3.0,NaN
12,3,2,0.78,NaN,0.77,NaN,0.77,NaN,3.0,NaN
13,4,2,0.73,NaN,0.75,NaN,0.77,NaN,3.0,NaN
14,5,2,0.72,NaN,0.78,NaN,0.77,NaN,3.0,NaN
15,1,2,0.77,NaN,0.98,NaN,0.92,NaN,4.0,NaN
16,2,3,0.94,NaN,0.95,NaN,0.94,NaN,4.0,NaN
17,3,3,0.93,NaN,0.92,NaN,0.95,NaN,4.0,NaN
18,4,3,0.94,NaN,0.88,NaN,0.94,NaN,4.0,NaN
19,5,3,0.92,NaN,0.93,NaN,0.95,NaN,4.0,NaN
20,1,3,1.03,NaN,1.04,NaN,1.04,NaN,5.0,NaN
21,2,3,1.00,NaN,1.01,NaN,1.02,NaN,5.0,NaN
22,3,3,1.03,NaN,1.03,NaN,1.05,NaN,5.0,NaN
23,4,3,1.02,NaN,1.03,NaN,1.03,NaN,5.0,NaN
24,5,3,1.04,NaN,1.05,NaN,1.03,NaN,5.0,NaN
25,1,4,1.08,NaN,1.09,NaN,1.07,NaN,6.0,NaN
26,2,4,1.03,NaN,1.05,NaN,1.05,NaN,6.0,NaN
27,3,4,1.09,NaN,1.07,NaN,1.08,NaN,6.0,NaN
28,4,4,1.05,NaN,1.05,NaN,1.06,NaN,6.0,NaN
29,5,4,1.06,NaN,1.08,NaN,1.08,NaN,6.0,NaN
30,1,4,1.12,NaN,1.11,NaN,1.09,NaN,7.0,NaN
31,2,4,1.13,NaN,1.19,NaN,1.16,NaN,7.0,NaN
32,3,4,1.15,NaN,1.13,NaN,1.19,NaN,7.0,NaN
33,4,4,1.18,NaN,1.19,NaN,1.15,NaN,7.0,NaN
34,5,4,1.17,NaN,1.18,NaN,1.18,NaN,7.0,NaN

In [72]:
original_df

,Plant No,Plant description,Plant 1,Plant 2,Plant 3,Unnamed: 5,Elisa score 1 OD,Elisa score 2 OD,Elisa score 2OD
0,1,Not innoculated,1.0,1.0,1.0,NaN,0.32,0.34,0.33
1,2,Not innoculated,1.0,1.0,1.0,NaN,0.35,0.33,0.33
2,3,Not innoculated,1.0,1.0,1.0,NaN,0.33,0.32,0.33
3,4,Not innoculated,1.0,1.0,1.0,NaN,0.34,0.31,0.33
4,5,Not innoculated,1.0,1.0,1.0,NaN,0.34,0.34,0.35
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,25th Feb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,innoculated with infection signs,1.0,2.0,1.0,NaN,0.42,0.85,0.44
8,2,innoculated with infection signs,1.0,1.0,1.0,NaN,0.45,0.55,0.48
9,3,innoculated with infection signs,1.0,1.0,1.0,NaN,0.52,0.52,0.43
10,4,innoculated with infection signs,1.0,2.0,1.0,NaN,0.39,0.54,0.45
11,5,innoculated with infection signs,1.0,1.0,1.0,NaN,0.39,0.45,0.43
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,4th March,Diseased state and visible symptoms,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1,Diseased state and visible symptoms,2.0,2.0,2.0,NaN,0.77,0.87,0.79
15,2,Diseased state and visible symptoms,2.0,2.0,3.0,NaN,0.74,0.73,0.74
16,3,Diseased state and visible symptoms,2.0,2.0,3.0,NaN,0.78,0.77,0.77
17,4,Diseased state and visible symptoms,2.0,2.0,2.0,NaN,0.73,0.75,0.77
18,5,Diseased state and visible symptoms,2.0,2.0,2.0,NaN,0.72,0.78,0.77
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,11th March,NaN,NaN,NaN,NaN,NaN,0.77,0.98,0.92
21,1,Diseased state with clear symptoms,2.0,3.0,3.0,NaN,0.94,0.95,0.94
22,2,Diseased state with clear symptoms,2.0,3.0,4.0,NaN,0.93,0.92,0.95
23,3,Diseased state with clear symptoms,3.0,3.0,4.0,NaN,0.94,0.88,0.94
24,4,Diseased state with clear symptoms,3.0,3.0,3.0,NaN,0.92,0.93,0.95
25,5,Diseased state with clear symptoms,3.0,3.0,4.0,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,18th March,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,Diseased state with full symptoms,3.0,3.0,4.0,NaN,1.03,1.04,1.04
29,NaN,Diseased state with full symptoms,3.0,4.0,4.0,NaN,1.00,1.01,1.02
30,NaN,Diseased state with full symptoms,3.0,3.0,4.0,NaN,1.03,1.03,1.05
31,NaN,Diseased state with full symptoms,3.0,4.0,4.0,NaN,1.02,1.03,1.03
32,NaN,Diseased state with full symptoms,3.0,4.0,4.0,NaN,1.04,1.05,1.03
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,25th March,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,Diseased state,4.0,4.0,4.0,NaN,1.08,1.09,1.07
36,NaN,Diseased state,4.0,4.0,4.0,NaN,1.03,1.05,1.05
37,NaN,Diseased state,4.0,4.0,4.0,NaN,1.09,1.07,1.08
38,NaN,Diseased state,4.0,4.0,4.0,NaN,1.05,1.05,1.06
39,NaN,Diseased state,4.0,4.0,4.0,NaN,1.06,1.08,1.08
40,2nd April,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,Termination,4.0,4.0,4.0,NaN,1.12,1.11,1.09
42,NaN,Termination,4.0,4.0,4.0,NaN,1.13,1.19,1.16
43,NaN,Termination,4.0,4.0,4.0,NaN,1.15,1.13,1.19
44,NaN,Termination,4.0,4.0,4.0,NaN,1.18,1.19,1.15
45,NaN,Termination,4.0,4.0,4.0,NaN,1.17,1.18,1.18

In [3]:
def _get_expert_file_BEANS(df_path:str) -> Tuple[pd.DataFrame]:
        """
        Cleans and formats beans expert readings

        Arg:
            df_path-> str: path to where the expert file csv is stored
        
        Return:
            dataframe -> pd.Dataframe: with consistent column alignment with the other expert files
        """

        beans_df = pd.read_excel(df_path)
        beans_df = beans_df.replace(r'^\s*$', np.nan, regex=True) # remove white space
        beans_df = beans_df.dropna(how='all').reset_index(drop=True) # drop rows with only NaNs
        
        # Annotate with appropriate week numbers
        first_col = beans_df.columns[0]
        date_mask = beans_df[first_col].astype(str).str.match(r'^\s*\d{1,2}(st|nd|rd|th)?\s+[A-Za-z]+\s*$', case=False, na=False)

        beans_df.loc[date_mask, 'week'] = range(1, date_mask.sum() + 1) # create week numbers from detected dates
        beans_df['week'] = beans_df['week'].ffill().fillna(0) # forward fill downwards and replace NaN with 0
        beans_df = beans_df[~date_mask].reset_index(drop=True) # remove date rows

        # Ensure weekly data alignment i.e. starting from 1 not 0
        beans_df['week'] = beans_df['week'] + 1

        # Handle cases of missing plant_numbers following the sequeeze of 1..5
        plant_col = 'Plant No'
        last_value = None
        for idx in beans_df.index:
            current = beans_df.loc[idx, plant_col] 
            # if current value exits, update tracker
            if pd.notna(current):
                last_value = int(current)
            # if Nan, continue sequence
            else:
                if last_value is None:
                    last_value = 1
                else:
                    last_value = (last_value % 5) + 1
                
                beans_df.loc[idx, plant_col] = last_value
        
        # drop empty columns
        beans_df = beans_df.dropna(axis=1, how='all')
        beans_df.columns = ['plant_number', 'disease_description', 'plant_1', 'plant_2', 'plant_3', 'elisa_score_1', 'elisa_score_2', 'elisa_score_3', 'week']
        beans_df = beans_df.drop(columns=['disease_description'])

        # compute score as mean of plant_* in df
        cols_to_average= [f'plant_{i+1}' for i in range(3)]
        beans_df['score'] = beans_df[cols_to_average].mean(axis=1).astype(int)
        beans_df = beans_df.drop(columns=cols_to_average) # drop plant columns

        # making l_* columns to ensure consistency with other expert reading files
        beans_df['l_1'], beans_df['l_2'], beans_df['l_3'] = (np.nan for _ in range(3))
        beans_df['disease_class'] = np.nan # disease_class to be updated

        # renaming colums
        elisa_rename_keys = {f'elisa_score_{i+1}': f'titer_{i+1}' for i in range(3)}
        beans_df = beans_df.rename(columns=elisa_rename_keys)

        # reordering the columns for consistent merger
        beans_df = beans_df[['plant_number', 'score', 'titer_1', 'l_1', 'titer_2', 'l_2', 'titer_3', 'l_3', 'week', 'disease_class']]
        return beans_df

_get_expert_file_BEANS(beans_expert_readings)

,plant_number,score,titer_1,l_1,titer_2,l_2,titer_3,l_3,week,disease_class
0,1,1,0.32,NaN,0.34,NaN,0.33,NaN,1.0,NaN
1,2,1,0.35,NaN,0.33,NaN,0.33,NaN,1.0,NaN
2,3,1,0.33,NaN,0.32,NaN,0.33,NaN,1.0,NaN
3,4,1,0.34,NaN,0.31,NaN,0.33,NaN,1.0,NaN
4,5,1,0.34,NaN,0.34,NaN,0.35,NaN,1.0,NaN
5,1,1,0.42,NaN,0.85,NaN,0.44,NaN,2.0,NaN
6,2,1,0.45,NaN,0.55,NaN,0.48,NaN,2.0,NaN
7,3,1,0.52,NaN,0.52,NaN,0.43,NaN,2.0,NaN
8,4,1,0.39,NaN,0.54,NaN,0.45,NaN,2.0,NaN
9,5,1,0.39,NaN,0.45,NaN,0.43,NaN,2.0,NaN
10,1,2,0.77,NaN,0.87,NaN,0.79,NaN,3.0,NaN
11,2,2,0.74,NaN,0.73,NaN,0.74,NaN,3.0,NaN
12,3,2,0.78,NaN,0.77,NaN,0.77,NaN,3.0,NaN
13,4,2,0.73,NaN,0.75,NaN,0.77,NaN,3.0,NaN
14,5,2,0.72,NaN,0.78,NaN,0.77,NaN,3.0,NaN
15,1,2,0.77,NaN,0.98,NaN,0.92,NaN,4.0,NaN
16,2,3,0.94,NaN,0.95,NaN,0.94,NaN,4.0,NaN
17,3,3,0.93,NaN,0.92,NaN,0.95,NaN,4.0,NaN
18,4,3,0.94,NaN,0.88,NaN,0.94,NaN,4.0,NaN
19,5,3,0.92,NaN,0.93,NaN,0.95,NaN,4.0,NaN
20,1,3,1.03,NaN,1.04,NaN,1.04,NaN,5.0,NaN
21,2,3,1.00,NaN,1.01,NaN,1.02,NaN,5.0,NaN
22,3,3,1.03,NaN,1.03,NaN,1.05,NaN,5.0,NaN
23,4,3,1.02,NaN,1.03,NaN,1.03,NaN,5.0,NaN
24,5,3,1.04,NaN,1.05,NaN,1.03,NaN,5.0,NaN
25,1,4,1.08,NaN,1.09,NaN,1.07,NaN,6.0,NaN
26,2,4,1.03,NaN,1.05,NaN,1.05,NaN,6.0,NaN
27,3,4,1.09,NaN,1.07,NaN,1.08,NaN,6.0,NaN
28,4,4,1.05,NaN,1.05,NaN,1.06,NaN,6.0,NaN
29,5,4,1.06,NaN,1.08,NaN,1.08,NaN,6.0,NaN
30,1,4,1.12,NaN,1.11,NaN,1.09,NaN,7.0,NaN
31,2,4,1.13,NaN,1.19,NaN,1.16,NaN,7.0,NaN
32,3,4,1.15,NaN,1.13,NaN,1.19,NaN,7.0,NaN
33,4,4,1.18,NaN,1.19,NaN,1.15,NaN,7.0,NaN
34,5,4,1.17,NaN,1.18,NaN,1.18,NaN,7.0,NaN